/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yuyan_utils_KMP */

#ifndef _Included_com_yuyan_utils_KMP
#define _Included_com_yuyan_utils_KMP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yuyan_utils_KMP
 * Method:    nativeFind
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yuyan_utils_KMP_nativeFind
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
