/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yuyan_driver_serialport_Serialport */

#ifndef _Included_com_yuyan_driver_serialport_Serialport
#define _Included_com_yuyan_driver_serialport_Serialport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yuyan_driver_serialport_Serialport
 * Method:    nativeOpen
 * Signature: ()Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_yuyan_driver_serialport_Serialport_nativeOpen(JNIEnv* env, jobject o);

/*
 * Class:     com_yuyan_driver_serialport_Serialport
 * Method:    nativeReadByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yuyan_driver_serialport_Serialport_nativeReadByte(JNIEnv* env, jobject o);

#ifdef __cplusplus
}
#endif
#endif
