/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yuyan_driver_serialport_Serialport */

#ifndef _Included_com_yuyan_driver_serialport_Serialport
#define _Included_com_yuyan_driver_serialport_Serialport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yuyan_driver_serialport_Serialport
 * Method:    nativeOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yuyan_driver_serialport_Serialport_nativeOpen
  (JNIEnv *, jobject);

/*
 * Class:     com_yuyan_driver_serialport_Serialport
 * Method:    nativeClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yuyan_driver_serialport_Serialport_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     com_yuyan_driver_serialport_Serialport
 * Method:    nativeRead
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_yuyan_driver_serialport_Serialport_nativeRead
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
