/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yuyan_driver_serialport_Serialport */

#ifndef _Included_com_yuyan_driver_serialport_Serialport
#define _Included_com_yuyan_driver_serialport_Serialport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yuyan_driver_serialport_Serialport
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yuyan_driver_serialport_Serialport_nativeOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_yuyan_driver_serialport_Serialport
 * Method:    nativeClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yuyan_driver_serialport_Serialport_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     com_yuyan_driver_serialport_Serialport
 * Method:    nativeGetStatus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_yuyan_driver_serialport_Serialport_nativeGetStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_yuyan_driver_serialport_Serialport
 * Method:    nativeRead
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_yuyan_driver_serialport_Serialport_nativeRead
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_yuyan_driver_serialport_Serialport
 * Method:    nativeWrite
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_yuyan_driver_serialport_Serialport_nativeWrite
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_yuyan_driver_serialport_Serialport
 * Method:    nativeSetReadTimeout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_yuyan_driver_serialport_Serialport_nativeSetReadTimeout
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
